#!/bin/zsh

alias a="ack-grep -k"
alias aa="ack-grep"
alias cp-prod="g co production && g pr && g cherry-pick master && g push && g co master"
alias cp-core-prod="g co core-production && g pr && g cherry-pick core-master && g push && g co core-master"
alias cp-prod-merge="g co production && g pr && g cherry-pick master -m 1 && g push && g co master"
alias du="du -hsc"
alias g="git"
alias gs="git s"
alias gg="gitg -c"
alias ls='ls --color=auto --human-readable'
alias ll='ls -l'
alias scr="/usr/bin/screen -D -RR"
alias serve="python -m SimpleHTTPServer 8081"
alias upgrade="sudo apt-get update && time sudo apt-get -y dist-upgrade"
alias canon-count="gphoto2 --get-config /main/status/shuttercounter"
alias mkdir="mkdir -p"

alias xvfb="xvfb-run --auto-servernum -w 1"

alias karma-chart="xvfb-run grunt karma:unit --tests='tests/{chart,stock,sparkline}/**/*.js'"
alias karma-chart-once="xvfb-run grunt karma:unit --tests='tests/{chart,stock,sparkline}/**/*.js' --single-run=true"

alias karma-all="xvfb-run grunt karma:unit --single-run=true"
alias karma-all-once="xvfb-run grunt karma:unit --single-run=true"

alias check-meta="node build/kendo-meta.js --check-deps kendo.all.js"
