#!/bin/zsh

alias ack="ack-grep"
alias cp-prod="git co production && git pr && git cherry-pick $1 && git push && git co master"
alias du="du -hsc"
alias g="git"
alias gg="gitg -c"
alias ls='ls --color=auto --human-readable'
alias ll='ls -l'
alias scr="/usr/bin/screen -D -RR"
alias serve="python -m SimpleHTTPServer 8081"
alias upgrade="sudo apt-get update && time sudo apt-get dist-upgrade"
